import Head from 'next/head';
import { Modal, RxBtn, Text } from '@/lib';
import NavBar from '@/comps/navbar';
import React from 'react';

export default function Home() {
	const [showModal, setShowModal] = React.useState(false);
	const handleClose = () => {
		setShowModal(false);
	};
	return (
		<>
			<Head>
				<title>R3D5 All Components</title>
				<meta
					name='description'
					content='Generated by Rex Edge Design Studio'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link
					rel='icon'
					href='/favicon.ico'
				/>
			</Head>
			<main className=''>
				<Modal
					show={showModal}
					onClose={handleClose}
				>
					<Modal.Header>Header</Modal.Header>
					<Modal.Body>This is the Body</Modal.Body>
					<Modal.Footer>Modal Footer</Modal.Footer>
				</Modal>
				<Text
					size={''}
					color={'text-purple-700'}
					type={''}
				>
					TEXT
				</Text>
				<RxBtn onClick={() => setShowModal(true)}>New Button</RxBtn>
				<NavBar />
			</main>
		</>
	);
}
